logging:
  level:
    root: INFO
    org.springframework.security.oauth2: DEBUG

security:
  ignored: 'oauth/authorize'
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
    authorization:
      checkTokenAccess: 'permitAll()'
      tokenKeyAccess: 'permitAll()'

