logging:
  level:
    root: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  h2.console:
    enabled: true
    path: "/h2"

security:
  # ignored: 'oauth/authorize'
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
    authorization:
      checkTokenAccess: 'permitAll()'
      tokenKeyAccess: 'permitAll()'

